### ISSUE TITLE
Add form field for link to MARC profile documentation

### ISSUE THREAD

**Issue by JohnMarkOckerbloom** [pod4lib/aggregator#806] opened 2022-05-12 17:31 UTC
Per prior discussion in issue #669, I'd like the "Provider details" tab under "Manage Organization" to include a new field with an editable link to providers' documentation on their MARC profiles.  This documentation may include information on how they express holdings, items, lendability, and BorrowDirect inclusion, and will in effect act as human-readable citable sources for some of the machine-readable item information already under this tab.  

This field should be editable by org owners (or POD admins), and be viewable (with a live link for the relevant URL) by any logged-in POD user.  Once it's in place, we can fill in links for each provider (most of them are on Google Docs now after James Robinson collected the information; at least one is on a provider's own website).

I brought up this functionality in today's POD-tech meeting, asking if providers were fine sharing this documentation with other members, and everyone I heard from was good with that.

**Comment by ggeisler** [comment] 2022-05-12 18:49
Duplicate of #555?

**Comment by JohnMarkOckerbloom** [comment] 2022-05-13 13:26
Yes, now that I look at it, this is basically #565 with a bit more operational detail.  Happy to fold this ticket into that one, but also would like it scheduled.  Thanks!

**Comment by ggeisler** [comment] 2022-05-13 16:25
Okay, I'm going to close this ticket then to prevent confusion with multiple tickets suggesting the same new feature. I don't see any info here that I'm not already aware of (this feature needs design before a developer should work on it because there are specifics that need defined: what is the new field label? does it need hint text to describe what it's for? how is the provided link displayed to other users?). #565 has the design needed label on it and it is already on my to-do list.

**Closed by ggeisler** 2022-05-13 16:25 UTC
